import Foundation

@available(macOS 12, iOS 15, *)
public enum DodamIconography: String {
    
    case arrowLeft             = "ArrowLeft"
    case b1ndLogo              = "B1NDLogo"
    case barChart              = "BarChart"
    case bell                  = "Bell"
    case bus                   = "Bus"
    case calendar              = "Calendar"
    case checkmark             = "Checkmark"
    case checkmarkCircle       = "CheckmarkCircle"
    case chevronLeft           = "ChevronLeft"
    case chevronRight          = "ChevronRight"
    case colorfulBus           = "ColorfulBus"
    case colorfulCalender      = "ColorfulCalender"
    case convenienceStore      = "ConvenienceStore"
    case doorOpen              = "DoorOpen"
    case exclamationmarkCircle = "ExclamationmarkCircle"
    case eye                   = "Eye"
    case eyeSlash              = "EyeSlash"
    case forkAndKnife          = "ForkAndKnife"
    case fullMoonFace          = "FullMoonFace"
    case gear                  = "Gear"
    case home                  = "Home"
    case logo                  = "Logo"
    case megaphone             = "Megaphone"
    case menu                  = "Menu"
    case moonPlus              = "MoonPlus"
    case note                  = "Note"
    case plus                  = "Plus"
    case tent                  = "Tent"
    case wakeupMegaphone       = "WakeupMegaphone"
    case wakeupNote            = "WakeupNote"
    case xmarkCircle           = "XmarkCircle"
}
