import Foundation

@available(macOS 12, iOS 15, *)
public enum DodamIconography: String {
    case arrowLeft             = "ArrowLeft"
    case b1ndLogo              = "B1NDLogo"
    case barChart              = "BarChart"
    case bell                  = "Bell"
    case bus                   = "Bus"
    case calendar              = "Calendar"
    case checkCircle           = "CheckCircle"
    case checkmark             = "Checkmark"
    case checkmarkCircle       = "CheckmarkCircle"
    case chevronDown           = "ChevronDown"
    case chevronLeft           = "ChevronLeft"
    case chevronRight          = "ChevronRight"
    case chevronUp             = "ChevronUp"
    case close                 = "Close"
    case clubMember            = "ClubMember"
    case colorfulBus           = "ColorfulBus"
    case colorfulCalender      = "ColorfulCalender"
    case convenienceStore      = "ConvenienceStore"
    case cookedRice            = "CookedRice"
    case crown                 = "Crown"
    case creditCard            = "CreditCard"
    case domomLogo             = "DomomLogo"
    case doorOpen              = "DoorOpen"
    case exclamationmarkCircle = "ExclamationmarkCircle"
    case eye                   = "Eye"
    case eyeSlash              = "EyeSlash"
    case forkAndKnife          = "ForkAndKnife"
    case fullMoonFace          = "FullMoonFace"
    case gear                  = "Gear"
    case handshake             = "Handshake"
    case home                  = "Home"
    case logo                  = "Logo"
    case magnifyingGlass       = "MagnifyingGlass"
    case megaphone             = "Megaphone"
    case menu                  = "Menu"
    case moonPlus              = "MoonPlus"
    case noneCheckCircle       = "NoneCheckCircle"
    case note                  = "Note"
    case pen                   = "Pen"
    case person                = "Person"
    case plus                  = "Plus"
    case redXmarkCircle        = "RedXmarkCircle"
    case smilingFace           = "SmilingFace"
    case tent                  = "Tent"
    case wakeupMegaphone       = "WakeupMegaphone"
    case wakeupNote            = "WakeupNote"
    case xmarkCircle           = "XmarkCircle"
    case yellowClock           = "YellowClock"
}
